### ISSUE TITLE
Support the dotty build

### ISSUE THREAD

**Issue by dwijnand** [coursier/sbt-launcher#56]
Just broke for me.  HEAD: 6ede81450. sbt.version: 1.2.7.  Using coursier/sbt-extras 5fb3c11d689d5aad1ead8c2ecf02e1177e5d6a88, which is coursier/sbt-launcher 1.2.9.

```
[error] java.lang.AssertionError: assertion failed: There should only be one ExactFilter(dotty-library_0.15) jar but found: Vector()
[error] 	at scala.Predef$.assert(Predef.scala:223)
[error] 	at dotty.tools.sbtplugin.DottyPlugin$.getJar(DottyPlugin.scala:392)
[error] 	at dotty.tools.sbtplugin.DottyPlugin$.$anonfun$projectSettings$16(DottyPlugin.scala:289)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.AssertionError: assertion failed: There should only be one ExactFilter(dotty-library_0.15) jar but found: Vector()
[error] 	at scala.Predef$.assert(Predef.scala:223)
[error] 	at dotty.tools.sbtplugin.DottyPlugin$.getJar(DottyPlugin.scala:392)
[error] 	at dotty.tools.sbtplugin.DottyPlugin$.$anonfun$projectSettings$16(DottyPlugin.scala:289)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.util.NoSuchElementException: key not found: (ch.epfl.lamp:dotty-doc_0.15,0.15.0-RC1)
[error] 	at scala.collection.MapLike.default(MapLike.scala:235)
[error] 	at scala.collection.MapLike.default$(MapLike.scala:234)
[error] 	at scala.collection.AbstractMap.default(Map.scala:63)
[error] 	at scala.collection.MapLike.apply(MapLike.scala:144)
[error] 	at scala.collection.MapLike.apply$(MapLike.scala:143)
[error] 	at scala.collection.AbstractMap.apply(Map.scala:63)
[error] 	at coursier.lmcoursier.ToSbt$.$anonfun$updateReport$1(ToSbt.scala:242)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:234)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:465)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at coursier.lmcoursier.ToSbt$.updateReport(ToSbt.scala:219)
[error] 	at coursier.lmcoursier.UpdateRun$.update(UpdateRun.scala:93)
[error] 	at coursier.lmcoursier.CoursierDependencyResolution.$anonfun$update$21(CoursierDependencyResolution.scala:196)
[error] 	at scala.util.Either.map(Either.scala:353)
[error] 	at coursier.lmcoursier.CoursierDependencyResolution.$anonfun$update$20(CoursierDependencyResolution.scala:193)
[error] 	at scala.util.Either.flatMap(Either.scala:341)
[error] 	at coursier.lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:191)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at dotty.tools.sbtplugin.DottyPlugin$.fetchArtifactsOf(DottyPlugin.scala:370)
[error] 	at dotty.tools.sbtplugin.DottyPlugin$.$anonfun$projectSettings$16(DottyPlugin.scala:285)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (dotty-compiler / scalaInstance) java.lang.AssertionError: assertion failed: There should only be one ExactFilter(dotty-library_0.15) jar but found: Vector()
[error] (dotty-doc / scalaInstance) java.lang.AssertionError: assertion failed: There should only be one ExactFilter(dotty-library_0.15) jar but found: Vector()
[error] (dotty-sbt-bridge / scalaInstance) java.util.NoSuchElementException: key not found: (ch.epfl.lamp:dotty-doc_0.15,0.15.0-RC1)
[error] Total time: 20 s, completed 29-May-2019 11:25:30
```

**Comment by dwijnand** [comment]
Switching to coursier sbt launcher 1.2.12, still breaks.
